on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create_recurring_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Fetch Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Deps
        run: pip3 install -r requirements.txt
      - name: Run Script
        run: python3 main.py
